import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration
 * Phase A2: Using autogeneration until content is created in Phase B
 * Phase B+: Will switch to structured sidebar based on chapter-index.md
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // TODO: Replace with structured sidebar once chapters are written
  // See specs/001-book-platform/chapter-index.md for full structure
};

export default sidebars;
